######################################################################
# Automatically generated by qmake (2.01a) mar jun 1 09:26:44 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += infomainwindow.h parser.h webinfo.h
SOURCES += infomainwindow.cpp main.cpp parser.cpp webinfo.cpp
RESOURCES += images.qrc
