######################################################################
# Automatically generated by qmake (2.01a) lun oct 19 09:42:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += infomainwindow.h parser.h webinfo.h
SOURCES += infomainwindow.cpp main.cpp parser.cpp webinfo.cpp
RESOURCES += images.qrc
