######################################################################
# Automatically generated by qmake (2.01a) sb dic 27 10:55:23 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


QT += script
CONFIG += uitools


# Input
SOURCES += main.cpp
