######################################################################
# Automatically generated by qmake (2.01a) lun oct 15 10:01:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buffer.h input.h list.h menubar.h process.h window.h
SOURCES += buffer.cpp \
           input.cpp \
           list.cpp \
           main.cpp \
           menubar.cpp \
           process.cpp \
           window.cpp
